const express = require('express');
const router = express.Router();
const Questions = require('../models/questions');
const Answers = require('../models/answers');

// References
// https://courses.lumenlearning.com/suny-osuniversityphysics/chapter/14-5-fluid-dynamics/#ex14.5
// https://courses.lumenlearning.com/suny-osuniversityphysics/chapter/14-6-bernoullis-equation/#CNX_UPhysics_Figure_14_06_TruckCar

// Temporary location to store questions information
var questions = [
  {question_id: '1', question_text: 'Calculate the buoyancy of an object with volume of \\( 3 \\ m^3 \\) that is completely submerged under water. Assume the density of water is \\( 997 \\ kg/m^3 \\) and acceleration due to gravity is \\( 9.81 \\ m / s^2 \\).'},
  {question_id: '2', question_text: 'A cruise ship weighs 165300 tonnes, is 200 metres long, 28 metres wide, and 50 metres high. How far below the waterline does the cruise ship extend? Assume the density of water is \\( 997 \\ kg/m^3 \\) and acceleration due to gravity is \\( 9.81 \\ m / s^2 \\).'},
  {question_id: '3', question_text: 'What kind of function describes the relationship between buoyancy and volume, assuming that mass and the density of the liquid remains the same?'},
  {question_id: '4', question_text: 'A ship slowly raises an iron anchor that is completely submerged in water. Assume the density of iron is \\( 7874 \\ kg/m^3 \\), and the density of water is \\( 997 \\ kg/m^3 \\). While pulling up the anchor, the tension on the chain is \\( 245000 \\ N \\)'},
  {question_id: '5', question_text: 'A balloon with a radius of \\( 0.5 \\ m^3 \\) is completely submerged under water. The balloon is filled with radon gase, which has a density of \\( 1.217 \\ kg/m^3 \\).Assume the density of water is \\( 997 \\ kg/m^3 \\) and acceleration due to gravity is \\( 9.81 \\ m / s^2 \\). What is the buoyancy of that balloon?'},
  {question_id: '6', question_text: 'What kind of function describes the relationship between fluid velocity from a larger area to a smaller area?'},
  {question_id: '7', question_text: 'A water hose with a radius of \\( 0.01 \\ m \\) has water flowing through it with a speed of \\( 1.5 \\ m/s \\). What will be the speed of the water flowing out of the nozzle of diameter \\( 0.005 \\ m \\)? Assume that water is incompressible.'},
  {question_id: '8', question_text: 'What kind of function describes the relationship between the cross-sectional area '},
  {question_id: '9', question_text: 'A wind tunnel with a radius of \\( 1 \\ m \\) has air flowing through it with a speed of \\( 5 \\ m/s \\). What will be the speed of the air flowing through the end of the wind tunnel with diameter of \\( 0.75 \\ m \\).'},
  {question_id: '10', question_text: 'A tunnel with a diameter of \\( 0.5 \\ m \\) has water flowing through at a speed of \\( 0.5 \\ m/s \\). The end of the tunnel tapers down into a smaller diameter. At the end of the tunnel, the water coming out of the tunnel was measured to be flowing at a speed of \\( 1 \\ m/s \\). What is the diameter of the end of the tunnel? Assume that water is incompressible.'},
  {question_id: '11', question_text: 'What kind of function describes the relationship between the pressure of an incompressible fluid and depth?'},
  {question_id: '12', question_text: 'What depth of water is required to produce a pressure of \\( 1 \\ atm \\). Assume the density of water is \\( 1000 \\ kg/m^3 \\) and \\( 1 \\ atm = 1.01 \\times 10^5 \\ N/m^2 \\)'},
  {question_id: '13', question_text: 'What depth of mercury is required to produce a pressure of \\( 1 \\ atm \\). Assume the density of mercury is \\( 13600 \\ kg/m^3 \\) and \\( 1 \\ atm = 1.01 \\times 10^5 \\ N/m^2 \\)'},
  {question_id: '14', question_text: 'Calculate the pressure due to a fluid, where the fluid is water with a density of \\( 1000 \\ kg/m^3 \\) and the depth is \\( 1 \\ km \\).'},
  {question_id: '15', question_text: 'Calculate the pressure due to a fluid, where the fluid is mercury with a density of \\( 13600 \\ kg/m^3 \\) and the depth is \\( 1 \\ km \\).'},
  {question_id: '16', question_text: 'Two large buildings next to each other have wind blowing between the buildings with a velocity of \\( 30 \\ m/s \\). What is the air pressure between the two buildings? Assume that the density of air is \\( 1.29 \\ kg/m^3 \\).'},
  {question_id: '17', question_text: 'What kind of function describes the relationship between the pressure and the velocity of a fluid?'},
  {question_id: '18', question_text: 'A nozzle with a diameter of \\( 0.5 \\ cm \\) is attached to a garden hose with a radius of \\( 0.9 \\ cm \\). The flow rate through the hose and nozzle is \\( 0.5 \\ L/s \\). Calculate the speed of the water in the hose. Assume the density of water is \\( 1000 \\ kg/m^3 \\).'},
  {question_id: '19', question_text: 'A nozzle with a diameter of \\( 0.5 \\ cm \\) is attached to a garden hose with a radius of \\( 0.9 \\ cm \\). The flow rate through the hose and nozzle is \\( 0.5 \\ L/s \\). Calculate the speed of the water in the nozzle. Assume the density of water is \\( 1000 \\ kg/m^3 \\).'},
  {question_id: '20', question_text: 'A nozzle with a diameter of \\( 0.5 \\ cm \\) is attached to a garden hose with a radius of \\( 0.9 \\ cm \\). The flow rate through the hose and nozzle is \\( 0.5 \\ L/s \\). Calculate the pressure in the hose, given that the absolute pressure in the nozzle is \\( 1.01 \\times 10^5 \\ N/m^2 \\).'},
  {question_id: '26', question_text: 'What kind of function describes the relationship between pressure as a function of force and the area that the force is applied?'},
  {question_id: '27', question_text: 'A hydraulic jack consists of a large cylinder of area \\( A \\) connected to a small cylinder of area \\( a \\). Both cylinders are filled with oil. When force \\( f \\) is applied to the small cylinder, the resulting pressure is transmitted to the large cylinder, which then exerts an upward force \\( F \\). Suppose a car of weight  \\( 12000 \\ N \\) rests on the large cylinder of area  \\( 0.10 \\ m^2 \\). What force must be applied to the small cylinder of area \\( 0.002 \\ m^2 \\) in order to support the car?'},
  {question_id: '28', question_text: 'What is the total net force acting on the surface of a dam of height \\( h \\) and width \\( w \\)?'},
  {question_id: '29', question_text: 'Suppose you are capable of carrying a weight of \\( 400 \\ N \\). What size cube of gold could you carry? Assume that the density of gold is \\( 19300 \\ kg/m^3 \\).'},
  {question_id: '30', question_text: 'A deep sea exploration vessel has a window of area \\( 0.10 \\ m^2 \\). What force is exerted on it by sea water at a depth of \\( 5000 \\ m \\)? Assume that the desnity of water is \\( l030 kg/m^3 \\).'},
  {question_id: '31', question_text: 'What range of values can the index of refraction be?'},
  {question_id: '32', question_text: 'What is the effect on the velocity of a vibrating string where the mass of the medium decreases?'},
  {question_id: '33', question_text: 'What is the effect on the velocity of sound waves as the density of the medium increases?'},
  {question_id: '34', question_text: 'What is the effect on the velocity of a vibrating string where the length of the string increases?'},
  {question_id: '35', question_text: 'What is the effect on the velocity of a vibrating string where the tension on the string increases?'},
  {question_id: '36', question_text: 'What slit spacing is required to give a separation of \\( 2 \\ cm \\) between the second and third order maxima for two slits if \\( \\lambda = 550 \\ nm \\) and \\( D = 1.50 \\ m \\)?'},
  {question_id: '37', question_text: 'When sodium yellow light ( \\( \\lambda \\ 589 \\ nm \\) ) is used in a double slit experi­ ment, the first-order maximum is (\\ 0.035 \\ cm \\) from the central maximum. When another light source of unknown wavelength is used, the first-order maximum occurs at \\( 0.032 \\ cm \\) from the center. What is this wavelength?'},
  {question_id: '38', question_text: 'Two narrow slits are separated by \\( 0.10 \\ mm \\) and are illuminated with light of wavelength \\( 550 \\ nm \\). A screen is placed \\( 2.2 \\ m \\) from the slits. What is the lateral separation of the first and second-order maxima on the screen?'},
  {question_id: '39', question_text: 'A Michelson interferometer is adapted to measure the displacement ofan ear drum when sound impinges on it. If green light ofwavelength \\( 552 \\ nm \\) is used and 94 fringes (dark to dark bands) pass by the detector, how far did the mirror move?'},
  {question_id: '40', question_text: 'Light of \\( 587.5 \\ nm \\) is used in a Michelson interferometer. When the mov­able mirror is moved, \\( 1780 \\) changes from dark to dark patterns are observed. How far was the mirror moved?'},
  {question_id: '41', question_text: 'The amplitude of two waves is given by \\( y_1(5) = 3 \\) and \\( y_2(5) = 5 \\). What is the ampitude of the sum of both waves at time of \\( 5 \\)?'},
  {question_id: '42', question_text: 'Two waves with frequency of \\( 100 \\ Hz \\) and \\( 90 \\ Hz \\) overlap at some region of space. What is the frequency of the beats heard?'},
  {question_id: '43', question_text: 'Two waves with frequency of \\( 100 \\ Hz \\) and \\( 90 \\ Hz \\) overlap at some region of space. What is the predominant frequency heard?'},
  {question_id: '44', question_text: 'A tuning fork vibrates at \\( 462 \\ Hz \\). An untuned violin string vibrates at \\( 457 \\ Hz \\). How much time elapses between successive beats?'},
  {question_id: '45', question_text: 'The amplitude of two waves is given by \\( y_1(10) = 5 \\) and \\( y_2(10) = -5 \\). What is the ampitude of the sum of both waves at time of \\( 10 \\)?'},
  {question_id: '46', question_text: '<placeholder text>'},
  {question_id: '47', question_text: '<placeholder text>'},
  {question_id: '48', question_text: '<placeholder text>'},
  {question_id: '49', question_text: '<placeholder text>'},
  {question_id: '50', question_text: '<placeholder text>'},
  {question_id: '51', question_text: '<placeholder text>'},
  {question_id: '52', question_text: '<placeholder text>'},
  {question_id: '53', question_text: '<placeholder text>'},
  {question_id: '54', question_text: '<placeholder text>'},
  {question_id: '55', question_text: '<placeholder text>'},
  {question_id: '56', question_text: '<placeholder text>'},
  {question_id: '57', question_text: '<placeholder text>'},
  {question_id: '58', question_text: '<placeholder text>'},
  {question_id: '59', question_text: '<placeholder text>'},
  {question_id: '60', question_text: '<placeholder text>'},
  {question_id: '61', question_text: '<placeholder text>'},
  {question_id: '62', question_text: '<placeholder text>'},
  {question_id: '63', question_text: '<placeholder text>'},
  {question_id: '64', question_text: '<placeholder text>'},
  {question_id: '65', question_text: '<placeholder text>'},
  {question_id: '66', question_text: '<placeholder text>'},
  {question_id: '67', question_text: '<placeholder text>'},
  {question_id: '68', question_text: '<placeholder text>'},
  {question_id: '69', question_text: '<placeholder text>'},
  {question_id: '70', question_text: '<placeholder text>'},
  {question_id: '71', question_text: '<placeholder text>'},
  {question_id: '72', question_text: '<placeholder text>'},
  {question_id: '73', question_text: '<placeholder text>'},
  {question_id: '74', question_text: '<placeholder text>'},
  {question_id: '75', question_text: '<placeholder text>'},
  {question_id: '76', question_text: '<placeholder text>'},
  {question_id: '77', question_text: '<placeholder text>'},
  {question_id: '78', question_text: '<placeholder text>'},
  {question_id: '79', question_text: '<placeholder text>'},
  {question_id: '80', question_text: '<placeholder text>'},
  {question_id: '81', question_text: '<placeholder text>'},
  {question_id: '82', question_text: '<placeholder text>'},
  {question_id: '83', question_text: '<placeholder text>'},
  {question_id: '84', question_text: '<placeholder text>'},
  {question_id: '85', question_text: '<placeholder text>'},
  {question_id: '86', question_text: '<placeholder text>'},
  {question_id: '87', question_text: '<placeholder text>'},
  {question_id: '88', question_text: '<placeholder text>'},
  {question_id: '89', question_text: '<placeholder text>'},
  {question_id: '90', question_text: '<placeholder text>'},
  {question_id: '91', question_text: '<placeholder text>'},
  {question_id: '92', question_text: '<placeholder text>'},
  {question_id: '93', question_text: '<placeholder text>'},
  {question_id: '94', question_text: '<placeholder text>'},
  {question_id: '95', question_text: '<placeholder text>'},
  {question_id: '96', question_text: '<placeholder text>'},
  {question_id: '97', question_text: '<placeholder text>'},
  {question_id: '98', question_text: '<placeholder text>'},
  {question_id: '99', question_text: '<placeholder text>'},
  {question_id: '100', question_text: '<placeholder text>'},
  {question_id: '101', question_text: '<placeholder text>'},
  {question_id: '102', question_text: '<placeholder text>'},
  {question_id: '103', question_text: '<placeholder text>'},
  {question_id: '104', question_text: '<placeholder text>'},
  {question_id: '105', question_text: '<placeholder text>'},
  {question_id: '106', question_text: '<placeholder text>'},
  {question_id: '107', question_text: '<placeholder text>'},
  {question_id: '108', question_text: '<placeholder text>'},
  {question_id: '109', question_text: '<placeholder text>'},
  {question_id: '110', question_text: '<placeholder text>'},
  {question_id: '111', question_text: '<placeholder text>'},
  {question_id: '112', question_text: '<placeholder text>'},
  {question_id: '113', question_text: '<placeholder text>'},
  {question_id: '114', question_text: '<placeholder text>'},
  {question_id: '115', question_text: '<placeholder text>'},
  {question_id: '116', question_text: '<placeholder text>'},
  {question_id: '117', question_text: '<placeholder text>'},
  {question_id: '118', question_text: '<placeholder text>'},
  {question_id: '119', question_text: '<placeholder text>'},
  {question_id: '120', question_text: '<placeholder text>'},
  {question_id: '121', question_text: '<placeholder text>'},
  {question_id: '122', question_text: '<placeholder text>'},
  {question_id: '123', question_text: '<placeholder text>'},
  {question_id: '124', question_text: '<placeholder text>'},
  {question_id: '125', question_text: '<placeholder text>'},
  {question_id: '126', question_text: '<placeholder text>'},
  {question_id: '127', question_text: '<placeholder text>'},
  {question_id: '128', question_text: '<placeholder text>'},
  {question_id: '129', question_text: '<placeholder text>'},
  {question_id: '130', question_text: '<placeholder text>'},
  {question_id: '131', question_text: '<placeholder text>'},
  {question_id: '132', question_text: '<placeholder text>'},
  {question_id: '133', question_text: '<placeholder text>'},
  {question_id: '134', question_text: '<placeholder text>'},
  {question_id: '135', question_text: '<placeholder text>'},
]

// Temporary location to store answers information
var answers = [
  {answer_id: '1', answer_text: '\\( 29341.71 \\ \\frac{kg \\cdot m}{s^2} \\)', question_id: '1', is_correct: true},
  {answer_id: '2', answer_text: '\\( 29341.71 \\ \\frac{s^2}{kg \\cdot m} \\)', question_id: '1', is_correct: false},
  {answer_id: '3', answer_text: '\\( 29341.71 \\ \\frac{kg \\cdot s^2}{m} \\)', question_id: '1', is_correct: false},
  {answer_id: '4', answer_text: '\\( 29341.71 \\ \\frac{m \\cdot s^2}{kg} \\)', question_id: '1', is_correct: false},
  {answer_id: '5', answer_text: '\\( 29341.71 \\ kg \\cdot m \\cdot s^2 \\)', question_id: '1', is_correct: false},
  {answer_id: '6', answer_text: '\\( 29.6 \\ m \\)', question_id: '2', is_correct: true},
  {answer_id: '7', answer_text: '\\( 0.03 \\ m \\)', question_id: '2', is_correct: false},
  {answer_id: '8', answer_text: '\\( 0.59 \\ m \\)', question_id: '2', is_correct: false},
  {answer_id: '9', answer_text: '\\( 3.02 \\ m \\)', question_id: '2', is_correct: false},
  {answer_id: '10', answer_text: '\\( 5.8 \\ m \\)', question_id: '2', is_correct: false},
  {answer_id: '11', answer_text: 'Linear function', question_id: '3', is_correct: true},
  {answer_id: '12', answer_text: 'Quadratic function', question_id: '3', is_correct: false},
  {answer_id: '13', answer_text: 'Cubic function', question_id: '3', is_correct: false},
  {answer_id: '14', answer_text: 'Quartic function', question_id: '3', is_correct: false},
  {answer_id: '15', answer_text: 'Quintic function', question_id: '3', is_correct: false},
  {answer_id: '16', answer_text: '\\( 280519 \\ N \\)', question_id: '4', is_correct: true},
  {answer_id: '17', answer_text: '\\( 1934935 N \\)', question_id: '4', is_correct: false},
  {answer_id: '18', answer_text: '\\( 2751892 N \\)', question_id: '4', is_correct: false},
  {answer_id: '19', answer_text: '\\( 245000 N \\)', question_id: '4', is_correct: false},
  {answer_id: '20', answer_text: '\\( 213978 N \\)', question_id: '4', is_correct: false},
  {answer_id: '21', answer_text: '\\( 5121 \\ \\frac{kg \\cdot m}{s^2} \\)', question_id: '5', is_correct: true},
  {answer_id: '22', answer_text: '\\( 5086 \\ N \\)', question_id: '5', is_correct: false},
  {answer_id: '23', answer_text: '\\( 4890 \\ N \\)', question_id: '5', is_correct: false},
  {answer_id: '24', answer_text: '\\( 4890 \\ \\frac{kg \\cdot m}{s^2} \\)', question_id: '5', is_correct: false},
  {answer_id: '25', answer_text: '\\( 6.2 \\ N \\)', question_id: '5', is_correct: false},
  {answer_id: '26', answer_text: 'Linear function', question_id: '6', is_correct: true},
  {answer_id: '27', answer_text: 'Quadratic function', question_id: '6', is_correct: false},
  {answer_id: '28', answer_text: 'Cubic function', question_id: '6', is_correct: false},
  {answer_id: '29', answer_text: 'Quartic function', question_id: '6', is_correct: false},
  {answer_id: '30', answer_text: 'Quintic function', question_id: '6', is_correct: false},
  {answer_id: '31', answer_text: '\\( 6 \\ m/s \\)', question_id: '7', is_correct: true},
  {answer_id: '32', answer_text: '\\( 3 \\ m/s \\)', question_id: '7', is_correct: false},
  {answer_id: '33', answer_text: '\\( 6 \\ cm/s \\)', question_id: '7', is_correct: false},
  {answer_id: '34', answer_text: 'Since water is incompressible the equation of continuity does not apply', question_id: '7', is_correct: false},
  {answer_id: '35', answer_text: '\\( 1.5 \\ m/s \\)', question_id: '7', is_correct: false},
  {answer_id: '36', answer_text: 'Linear function', question_id: '8', is_correct: true},
  {answer_id: '37', answer_text: 'Quadratic function', question_id: '8', is_correct: false},
  {answer_id: '38', answer_text: 'Cubic function', question_id: '8', is_correct: false},
  {answer_id: '39', answer_text: 'Quartic function', question_id: '8', is_correct: false},
  {answer_id: '40', answer_text: 'Quintic function', question_id: '8', is_correct: false},
  {answer_id: '41', answer_text: 'Since air is compressible the equation of continuity does not apply', question_id: '9', is_correct: true},
  {answer_id: '42', answer_text: '\\( 8.89 \\ m/s \\)', question_id: '9', is_correct: false},
  {answer_id: '43', answer_text: '\\( 6.67 \\ m/s \\)', question_id: '9', is_correct: false},
  {answer_id: '44', answer_text: '\\( 8.89 \\ cm/s \\)', question_id: '9', is_correct: false},
  {answer_id: '45', answer_text: '\\( 5 \\ m/s \\)', question_id: '9', is_correct: false},
  {answer_id: '46', answer_text: '\\( 0.35 \\ m/s \\)', question_id: '10', is_correct: true},
  {answer_id: '47', answer_text: 'Since water is incompressible the equation of continuity does not apply', question_id: '10', is_correct: false},
  {answer_id: '48', answer_text: '\\( 0.5 \\ m/s \\)', question_id: '10', is_correct: false},
  {answer_id: '49', answer_text: '\\( 0.35 \\ cm/s \\)', question_id: '10', is_correct: false},
  {answer_id: '50', answer_text: '\\( 1.0 \\ m/s \\)', question_id: '10', is_correct: false},
  {answer_id: '51', answer_text: 'Linear function', question_id: '11', is_correct: true},
  {answer_id: '52', answer_text: 'Quadratic function', question_id: '11', is_correct: false},
  {answer_id: '53', answer_text: 'Cubic function', question_id: '11', is_correct: false},
  {answer_id: '54', answer_text: 'Quartic function', question_id: '11', is_correct: false},
  {answer_id: '55', answer_text: 'Quintic function', question_id: '11', is_correct: false},
  {answer_id: '56', answer_text: '\\( 1030 \\ cm \\)', question_id: '12', is_correct: true},
  {answer_id: '57', answer_text: '\\( 1.02 \\times 10^{-4} m \\)', question_id: '12', is_correct: false},
  {answer_id: '58', answer_text: '\\( 10.3 \\ N/m^2 \\)', question_id: '12', is_correct: false},
  {answer_id: '59', answer_text: '\\( 1.03 \\ m \\)', question_id: '12', is_correct: false},
  {answer_id: '60', answer_text: '\\( 10 \\ m \\)', question_id: '12', is_correct: false},
  {answer_id: '61', answer_text: '\\( 76 \\ cm \\)', question_id: '13', is_correct: true},
  {answer_id: '62', answer_text: '\\( 7.5 \\times 10^{-6} \\ m \\)', question_id: '13', is_correct: false},
  {answer_id: '63', answer_text: '\\( 0.7 \\ m \\)', question_id: '13', is_correct: false},
  {answer_id: '64', answer_text: '\\( 7.6 \\ cm \\)', question_id: '13', is_correct: false},
  {answer_id: '65', answer_text: '\\( 7.6 \\ m \\)', question_id: '13', is_correct: false},
  {answer_id: '66', answer_text: '\\( 9810000 \\ N/m^2 \\)', question_id: '14', is_correct: true},
  {answer_id: '67', answer_text: '\\( 981000 \\ Pa \\)', question_id: '14', is_correct: false},
  {answer_id: '68', answer_text: '\\( 9810 \\ Pa \\)', question_id: '14', is_correct: false},
  {answer_id: '69', answer_text: '\\( 98100 \\ N/m^2 \\)', question_id: '14', is_correct: false},
  {answer_id: '70', answer_text: '\\( 981000 \\ N/m^2 \\)', question_id: '14', is_correct: false},
  {answer_id: '71', answer_text: '\\( 133416000 \\ N/m^2 \\)', question_id: '15', is_correct: true},
  {answer_id: '72', answer_text: '\\( 133416 \\ N/m^2 \\)', question_id: '15', is_correct: false},
  {answer_id: '73', answer_text: '\\( 13341600 \\ Pa \\)', question_id: '15', is_correct: false},
  {answer_id: '74', answer_text: '\\( 133416 \\ Pa \\)', question_id: '15', is_correct: false},
  {answer_id: '75', answer_text: '\\( 1334160000 \\ N/m^2 \\)', question_id: '15', is_correct: false},
  {answer_id: '76', answer_text: '\\( 580.5 \\ Pa \\)', question_id: '16', is_correct: true},
  {answer_id: '77', answer_text: '\\( 1161 \\ Pa \\)', question_id: '16', is_correct: false},
  {answer_id: '78', answer_text: '\\( 585 \\ Pa \\)', question_id: '16', is_correct: false},
  {answer_id: '79', answer_text: '\\( 1170 \\ Pa \\)', question_id: '16', is_correct: false},
  {answer_id: '80', answer_text: '\\( 580.5 \\ m/s \\)', question_id: '16', is_correct: false},
  {answer_id: '81', answer_text: 'Quadratic function', question_id: '17', is_correct: true},
  {answer_id: '82', answer_text: 'Linear function', question_id: '17', is_correct: false},
  {answer_id: '83', answer_text: 'Cubic function', question_id: '17', is_correct: false},
  {answer_id: '84', answer_text: 'Quartic function', question_id: '17', is_correct: false},
  {answer_id: '85', answer_text: 'Quintic function', question_id: '17', is_correct: false},
  {answer_id: '86', answer_text: '\\( 1.96 \\ m/s \\)', question_id: '18', is_correct: true},
  {answer_id: '87', answer_text: '\\( 0.0177 \\ m/s \\)', question_id: '18', is_correct: false},
  {answer_id: '88', answer_text: '\\( 1.77 \\times 10^{-4} \\ m/s \\)', question_id: '18', is_correct: false},
  {answer_id: '89', answer_text: '\\( 1.96 \\times 10^{-4} \\ m/s \\)', question_id: '18', is_correct: false},
  {answer_id: '90', answer_text: '\\( 177 \\ m/s \\)', question_id: '18', is_correct: false},
  {answer_id: '91', answer_text: '\\( 25.5 \\ m/s \\)', question_id: '19', is_correct: true},
  {answer_id: '92', answer_text: '\\( 6.37 \\ m/s \\)', question_id: '19', is_correct: false},
  {answer_id: '93', answer_text: '\\( 0.0318 \\ m/s \\)', question_id: '19', is_correct: false},
  {answer_id: '94', answer_text: '\\( 25.5 \\times 10^{-4} \\ m/s \\)', question_id: '19', is_correct: false},
  {answer_id: '95', answer_text: '\\( 6.37 \\times 10^{-4} \\ m/s \\)', question_id: '19', is_correct: false},
  {answer_id: '96', answer_text: '\\( 4.24 \\times 10^5 \\ N/m^2 \\)', question_id: '20', is_correct: true},
  {answer_id: '97', answer_text: '\\( 1.13 \\times 10^5 \\ N/m^2 \\)', question_id: '20', is_correct: false},
  {answer_id: '98', answer_text: '\\( 3.30 \\times 10^10 \\ N/s^2 \\)', question_id: '20', is_correct: false},
  {answer_id: '99', answer_text: '\\( 1.15 \\times 10^5 \\ N/s^2 \\)', question_id: '20', is_correct: false},
  {answer_id: '100', answer_text: '\\( 3.30 \\times 10^5 \\ N/s^2 \\)', question_id: '20', is_correct: false},
  {answer_id: '126', answer_text: 'Linear function', question_id: '26', is_correct: true},
  {answer_id: '127', answer_text: 'Quadratic function', question_id: '26', is_correct: false},
  {answer_id: '128', answer_text: 'Cubic function', question_id: '26', is_correct: false},
  {answer_id: '129', answer_text: 'Quartic function', question_id: '26', is_correct: false},
  {answer_id: '130', answer_text: 'Quintic function', question_id: '26', is_correct: false},
  {answer_id: '131', answer_text: '\\( 240 \\ N \\)', question_id: '27', is_correct: true},
  {answer_id: '132', answer_text: '\\( 4.8 \\ N \\)', question_id: '27', is_correct: false},
  {answer_id: '133', answer_text: '\\( 4.17 \\times 10^{-3} \\)', question_id: '27', is_correct: false},
  {answer_id: '134', answer_text: '\\( 0.21 N \\)', question_id: '27', is_correct: false},
  {answer_id: '135', answer_text: '\\( 24 \\ N \\)', question_id: '27', is_correct: false},
  {answer_id: '136', answer_text: '\\( \\frac{\\rho g w h^2}{2} \\)', question_id: '28', is_correct: true},
  {answer_id: '137', answer_text: '\\( \\rho g w h \\)', question_id: '28', is_correct: false},
  {answer_id: '138', answer_text: '\\( \\frac{2}{\\rho g w h^2} \\)', question_id: '28', is_correct: false},
  {answer_id: '139', answer_text: '\\( \\frac{\\rho g h^2}{w} \\)', question_id: '28', is_correct: false},
  {answer_id: '140', answer_text: '\\( \\frac{\\rho g h^2}{2} \\)', question_id: '28', is_correct: false},
  {answer_id: '141', answer_text: '\\( 0.13 \\ m \\ wide \\)', question_id: '29', is_correct: true},
  {answer_id: '142', answer_text: '\\( 0.002 \\ m \\ wide \\)', question_id: '29', is_correct: false},
  {answer_id: '143', answer_text: '\\( 0.002 \\ cm \\ wide \\)', question_id: '29', is_correct: false},
  {answer_id: '144', answer_text: '\\( 0.046 \\ m \\ wide \\)', question_id: '29', is_correct: false},
  {answer_id: '145', answer_text: '\\( 46 \\ cm \\ wide \\)', question_id: '29', is_correct: false},
  {answer_id: '146', answer_text: '\\( 5.05 \\times 10^6 \\ N \\)', question_id: '30', is_correct: true},
  {answer_id: '147', answer_text: '\\( 5.05 \\times 10^5 \\ N \\)', question_id: '30', is_correct: false},
  {answer_id: '148', answer_text: '\\( 5.05 \\times 10^4 \\ N \\)', question_id: '30', is_correct: false},
  {answer_id: '149', answer_text: '\\( 1.60 \\times 10^7 \\ N \\)', question_id: '30', is_correct: false},
  {answer_id: '150', answer_text: '\\( 1.60 \\times 10^6 \\ N \\)', question_id: '30', is_correct: false},
  {answer_id: '151', answer_text: '\\( n \\geq 1 \\)', question_id: '31', is_correct: true},
  {answer_id: '152', answer_text: '\\( n = 1 \\)', question_id: '31', is_correct: false},
  {answer_id: '153', answer_text: '\\( n \\leq 1 \\)', question_id: '31', is_correct: false},
  {answer_id: '154', answer_text: '\\( n \\geq 0 \\)', question_id: '31', is_correct: false},
  {answer_id: '155', answer_text: '\\( n \\leq 0 \\)', question_id: '31', is_correct: false},
  {answer_id: '156', answer_text: 'Wave velocity increases', question_id: '32', is_correct: true},
  {answer_id: '157', answer_text: 'Wave velocity decreases', question_id: '32', is_correct: false},
  {answer_id: '158', answer_text: 'Wave velocity remains the same', question_id: '32', is_correct: false},
  {answer_id: '159', answer_text: 'Wave velocity increases only up to a point', question_id: '32', is_correct: false},
  {answer_id: '160', answer_text: 'Wave velocity decreases only up to a point', question_id: '32', is_correct: false},
  {answer_id: '161', answer_text: 'Sound velocity increases', question_id: '33', is_correct: true},
  {answer_id: '162', answer_text: 'Sound velocity decreases', question_id: '33', is_correct: false},
  {answer_id: '163', answer_text: 'Sound velocity remains the same', question_id: '33', is_correct: false},
  {answer_id: '164', answer_text: 'Sound velocity increases only up to a point', question_id: '33', is_correct: false},
  {answer_id: '165', answer_text: 'Sound velocity decreases only up to a point', question_id: '33', is_correct: false},
  {answer_id: '166', answer_text: 'Wave velocity increases', question_id: '34', is_correct: true},
  {answer_id: '167', answer_text: 'Wave velocity decreases', question_id: '34', is_correct: false},
  {answer_id: '168', answer_text: 'Wave velocity remains the same', question_id: '34', is_correct: false},
  {answer_id: '169', answer_text: 'Wave velocity increases only up to a point', question_id: '34', is_correct: false},
  {answer_id: '170', answer_text: 'Wave velocity decreases only up to a point', question_id: '34', is_correct: false},
  {answer_id: '171', answer_text: 'Wave velocity increases', question_id: '35', is_correct: true},
  {answer_id: '172', answer_text: 'Wave velocity decreases', question_id: '35', is_correct: false},
  {answer_id: '173', answer_text: 'Wave velocity remains the same', question_id: '35', is_correct: false},
  {answer_id: '174', answer_text: 'Wave velocity increases only up to a point', question_id: '35', is_correct: false},
  {answer_id: '175', answer_text: 'Wave velocity decreases only up to a point', question_id: '35', is_correct: false},
  {answer_id: '176', answer_text: '\\( 0.041 \\ mm \\)', question_id: '36', is_correct: true},
  {answer_id: '177', answer_text: '\\( 41250 \\ mm \\)', question_id: '36', is_correct: false},
  {answer_id: '178', answer_text: '\\( 41.25 \\ m \\)', question_id: '36', is_correct: false},
  {answer_id: '179', answer_text: '\\( 0.041 \\ cm \\)', question_id: '36', is_correct: false},
  {answer_id: '180', answer_text: '\\( 0.041 \\ m \\)', question_id: '36', is_correct: false},
  {answer_id: '181', answer_text: '\\( 539 \\ nm \\)', question_id: '37', is_correct: true},
  {answer_id: '182', answer_text: '\\( 644 \\ nm \\)', question_id: '37', is_correct: false},
  {answer_id: '183', answer_text: '\\( 0.66 \\ cm \\)', question_id: '37', is_correct: false},
  {answer_id: '184', answer_text: '\\( 539 \\ cm \\)', question_id: '37', is_correct: false},
  {answer_id: '185', answer_text: '\\( 660 \\ nm \\)', question_id: '37', is_correct: false},
  {answer_id: '186', answer_text: '\\( 1.1 \\ mm \\)', question_id: '38', is_correct: true},
  {answer_id: '187', answer_text: '\\( 12100 \\ nm \\)', question_id: '38', is_correct: false},
  {answer_id: '188', answer_text: '\\( 12100 \\ mm \\)', question_id: '38', is_correct: false},
  {answer_id: '189', answer_text: '\\( 1.2 \\ mm \\)', question_id: '38', is_correct: false},
  {answer_id: '190', answer_text: '\\( 1.2 \\ nm \\)', question_id: '38', is_correct: false},
  {answer_id: '191', answer_text: '\\( 2.59 \\times 10^{-5} \\ m \\)', question_id: '39', is_correct: true},
  {answer_id: '192', answer_text: '\\( 2.59 \\ mm \\)', question_id: '39', is_correct: false},
  {answer_id: '193', answer_text: '\\( 2.59 \\ cm \\)', question_id: '39', is_correct: false},
  {answer_id: '194', answer_text: '\\( 2.59 \\times 10^{-3} \\ m \\)', question_id: '39', is_correct: false},
  {answer_id: '195', answer_text: '\\( 2.59 \\times 10^{-4} \\ m \\)', question_id: '39', is_correct: false},
  {answer_id: '196', answer_text: '\\( 5.229 \\times 10^{-4} \\ m \\)', question_id: '40', is_correct: true},
  {answer_id: '197', answer_text: '\\( 5.229 \\ cm \\)', question_id: '40', is_correct: false},
  {answer_id: '198', answer_text: '\\( 5.229 \\ m \\)', question_id: '40', is_correct: false},
  {answer_id: '199', answer_text: '\\( 5.229 \\times 10^{-3} \\ m\\)', question_id: '40', is_correct: false},
  {answer_id: '200', answer_text: '\\( 5.229 \\times 10^{4} \\ nm \\)', question_id: '40', is_correct: false},
  {answer_id: '201', answer_text: '\\( 8 \\)', question_id: '41', is_correct: true},
  {answer_id: '202', answer_text: '\\( 2 \\)', question_id: '41', is_correct: false},
  {answer_id: '203', answer_text: '\\( -2 \\)', question_id: '41', is_correct: false},
  {answer_id: '204', answer_text: '\\( -8 \\)', question_id: '41', is_correct: false},
  {answer_id: '205', answer_text: '\\( 5 \\)', question_id: '41', is_correct: false},
  {answer_id: '206', answer_text: '\\( 10 \\ Hz \\)', question_id: '42', is_correct: true},
  {answer_id: '207', answer_text: '\\( -10 \\ Hz \\)', question_id: '42', is_correct: false},
  {answer_id: '208', answer_text: '\\( 100 \\ Hz \\)', question_id: '42', is_correct: false},
  {answer_id: '209', answer_text: '\\( 90 \\ Hz \\)', question_id: '42', is_correct: false},
  {answer_id: '210', answer_text: '\\( 0 \\ Hz \\)', question_id: '42', is_correct: false},
  {answer_id: '211', answer_text: '\\( 95 \\ Hz \\)', question_id: '43', is_correct: true},
  {answer_id: '212', answer_text: '\\( 5 \\ Hz \\)', question_id: '43', is_correct: false},
  {answer_id: '213', answer_text: '\\( 10 \\ Hz \\)', question_id: '43', is_correct: false},
  {answer_id: '214', answer_text: '\\( 100 \\ Hz \\)', question_id: '43', is_correct: false},
  {answer_id: '215', answer_text: '\\( 90 \\ Hz \\)', question_id: '43', is_correct: false},
  {answer_id: '216', answer_text: '\\( 0.2 \\ s \\)', question_id: '44', is_correct: true},
  {answer_id: '217', answer_text: '\\( 5 \\ s \\)', question_id: '44', is_correct: false},
  {answer_id: '218', answer_text: '\\( 5 \\ Hz \\)', question_id: '44', is_correct: false},
  {answer_id: '219', answer_text: '\\( 0.2 \\ Hz \\)', question_id: '44', is_correct: false},
  {answer_id: '220', answer_text: '\\( 2 \\ s \\)', question_id: '44', is_correct: false},
  {answer_id: '221', answer_text: '\\( 0 \\)', question_id: '45', is_correct: true},
  {answer_id: '222', answer_text: '\\( 5 \\)', question_id: '45', is_correct: false},
  {answer_id: '223', answer_text: '\\( -5 \\)', question_id: '45', is_correct: false},
  {answer_id: '224', answer_text: '\\( 10 \\)', question_id: '45', is_correct: false},
  {answer_id: '225', answer_text: '\\( -10 \\)', question_id: '45', is_correct: false},
  {answer_id: '226', answer_text: '<placeholder text>', question_id: '46', is_correct: true},
  {answer_id: '227', answer_text: '<placeholder text>', question_id: '46', is_correct: false},
  {answer_id: '228', answer_text: '<placeholder text>', question_id: '46', is_correct: false},
  {answer_id: '229', answer_text: '<placeholder text>', question_id: '46', is_correct: false},
  {answer_id: '230', answer_text: '<placeholder text>', question_id: '46', is_correct: false},
  {answer_id: '231', answer_text: '<placeholder text>', question_id: '47', is_correct: true},
  {answer_id: '232', answer_text: '<placeholder text>', question_id: '47', is_correct: false},
  {answer_id: '233', answer_text: '<placeholder text>', question_id: '47', is_correct: false},
  {answer_id: '234', answer_text: '<placeholder text>', question_id: '47', is_correct: false},
  {answer_id: '235', answer_text: '<placeholder text>', question_id: '47', is_correct: false},
  {answer_id: '236', answer_text: '<placeholder text>', question_id: '48', is_correct: true},
  {answer_id: '237', answer_text: '<placeholder text>', question_id: '48', is_correct: false},
  {answer_id: '238', answer_text: '<placeholder text>', question_id: '48', is_correct: false},
  {answer_id: '239', answer_text: '<placeholder text>', question_id: '48', is_correct: false},
  {answer_id: '240', answer_text: '<placeholder text>', question_id: '48', is_correct: false},
  {answer_id: '241', answer_text: '<placeholder text>', question_id: '49', is_correct: true},
  {answer_id: '242', answer_text: '<placeholder text>', question_id: '49', is_correct: false},
  {answer_id: '243', answer_text: '<placeholder text>', question_id: '49', is_correct: false},
  {answer_id: '244', answer_text: '<placeholder text>', question_id: '49', is_correct: false},
  {answer_id: '245', answer_text: '<placeholder text>', question_id: '49', is_correct: false},
  {answer_id: '246', answer_text: '<placeholder text>', question_id: '50', is_correct: true},
  {answer_id: '247', answer_text: '<placeholder text>', question_id: '50', is_correct: false},
  {answer_id: '248', answer_text: '<placeholder text>', question_id: '50', is_correct: false},
  {answer_id: '249', answer_text: '<placeholder text>', question_id: '50', is_correct: false},
  {answer_id: '250', answer_text: '<placeholder text>', question_id: '50', is_correct: false},
  {answer_id: '251', answer_text: '<placeholder text>', question_id: '51', is_correct: true},
  {answer_id: '252', answer_text: '<placeholder text>', question_id: '51', is_correct: false},
  {answer_id: '253', answer_text: '<placeholder text>', question_id: '51', is_correct: false},
  {answer_id: '254', answer_text: '<placeholder text>', question_id: '51', is_correct: false},
  {answer_id: '255', answer_text: '<placeholder text>', question_id: '51', is_correct: false},
  {answer_id: '256', answer_text: '<placeholder text>', question_id: '52', is_correct: true},
  {answer_id: '257', answer_text: '<placeholder text>', question_id: '52', is_correct: false},
  {answer_id: '258', answer_text: '<placeholder text>', question_id: '52', is_correct: false},
  {answer_id: '259', answer_text: '<placeholder text>', question_id: '52', is_correct: false},
  {answer_id: '260', answer_text: '<placeholder text>', question_id: '52', is_correct: false},
  {answer_id: '261', answer_text: '<placeholder text>', question_id: '53', is_correct: true},
  {answer_id: '262', answer_text: '<placeholder text>', question_id: '53', is_correct: false},
  {answer_id: '263', answer_text: '<placeholder text>', question_id: '53', is_correct: false},
  {answer_id: '264', answer_text: '<placeholder text>', question_id: '53', is_correct: false},
  {answer_id: '265', answer_text: '<placeholder text>', question_id: '53', is_correct: false},
  {answer_id: '266', answer_text: '<placeholder text>', question_id: '54', is_correct: true},
  {answer_id: '267', answer_text: '<placeholder text>', question_id: '54', is_correct: false},
  {answer_id: '268', answer_text: '<placeholder text>', question_id: '54', is_correct: false},
  {answer_id: '269', answer_text: '<placeholder text>', question_id: '54', is_correct: false},
  {answer_id: '270', answer_text: '<placeholder text>', question_id: '54', is_correct: false},
  {answer_id: '271', answer_text: '<placeholder text>', question_id: '55', is_correct: true},
  {answer_id: '272', answer_text: '<placeholder text>', question_id: '55', is_correct: false},
  {answer_id: '273', answer_text: '<placeholder text>', question_id: '55', is_correct: false},
  {answer_id: '274', answer_text: '<placeholder text>', question_id: '55', is_correct: false},
  {answer_id: '275', answer_text: '<placeholder text>', question_id: '55', is_correct: false},
  {answer_id: '276', answer_text: '<placeholder text>', question_id: '56', is_correct: true},
  {answer_id: '277', answer_text: '<placeholder text>', question_id: '56', is_correct: false},
  {answer_id: '278', answer_text: '<placeholder text>', question_id: '56', is_correct: false},
  {answer_id: '279', answer_text: '<placeholder text>', question_id: '56', is_correct: false},
  {answer_id: '280', answer_text: '<placeholder text>', question_id: '56', is_correct: false},
  {answer_id: '281', answer_text: '<placeholder text>', question_id: '57', is_correct: true},
  {answer_id: '282', answer_text: '<placeholder text>', question_id: '57', is_correct: false},
  {answer_id: '283', answer_text: '<placeholder text>', question_id: '57', is_correct: false},
  {answer_id: '284', answer_text: '<placeholder text>', question_id: '57', is_correct: false},
  {answer_id: '285', answer_text: '<placeholder text>', question_id: '57', is_correct: false},
  {answer_id: '286', answer_text: '<placeholder text>', question_id: '58', is_correct: true},
  {answer_id: '287', answer_text: '<placeholder text>', question_id: '58', is_correct: false},
  {answer_id: '288', answer_text: '<placeholder text>', question_id: '58', is_correct: false},
  {answer_id: '289', answer_text: '<placeholder text>', question_id: '58', is_correct: false},
  {answer_id: '290', answer_text: '<placeholder text>', question_id: '58', is_correct: false},
  {answer_id: '291', answer_text: '<placeholder text>', question_id: '59', is_correct: true},
  {answer_id: '292', answer_text: '<placeholder text>', question_id: '59', is_correct: false},
  {answer_id: '293', answer_text: '<placeholder text>', question_id: '59', is_correct: false},
  {answer_id: '294', answer_text: '<placeholder text>', question_id: '59', is_correct: false},
  {answer_id: '295', answer_text: '<placeholder text>', question_id: '59', is_correct: false},
  {answer_id: '296', answer_text: '<placeholder text>', question_id: '60', is_correct: true},
  {answer_id: '297', answer_text: '<placeholder text>', question_id: '60', is_correct: false},
  {answer_id: '298', answer_text: '<placeholder text>', question_id: '60', is_correct: false},
  {answer_id: '299', answer_text: '<placeholder text>', question_id: '60', is_correct: false},
  {answer_id: '300', answer_text: '<placeholder text>', question_id: '60', is_correct: false},
  {answer_id: '301', answer_text: '<placeholder text>', question_id: '61', is_correct: true},
  {answer_id: '302', answer_text: '<placeholder text>', question_id: '61', is_correct: false},
  {answer_id: '303', answer_text: '<placeholder text>', question_id: '61', is_correct: false},
  {answer_id: '304', answer_text: '<placeholder text>', question_id: '61', is_correct: false},
  {answer_id: '305', answer_text: '<placeholder text>', question_id: '61', is_correct: false},
  {answer_id: '306', answer_text: '<placeholder text>', question_id: '62', is_correct: true},
  {answer_id: '307', answer_text: '<placeholder text>', question_id: '62', is_correct: false},
  {answer_id: '308', answer_text: '<placeholder text>', question_id: '62', is_correct: false},
  {answer_id: '309', answer_text: '<placeholder text>', question_id: '62', is_correct: false},
  {answer_id: '310', answer_text: '<placeholder text>', question_id: '62', is_correct: false},
  {answer_id: '311', answer_text: '<placeholder text>', question_id: '63', is_correct: true},
  {answer_id: '312', answer_text: '<placeholder text>', question_id: '63', is_correct: false},
  {answer_id: '313', answer_text: '<placeholder text>', question_id: '63', is_correct: false},
  {answer_id: '314', answer_text: '<placeholder text>', question_id: '63', is_correct: false},
  {answer_id: '315', answer_text: '<placeholder text>', question_id: '63', is_correct: false},
  {answer_id: '316', answer_text: '<placeholder text>', question_id: '64', is_correct: true},
  {answer_id: '317', answer_text: '<placeholder text>', question_id: '64', is_correct: false},
  {answer_id: '318', answer_text: '<placeholder text>', question_id: '64', is_correct: false},
  {answer_id: '319', answer_text: '<placeholder text>', question_id: '64', is_correct: false},
  {answer_id: '320', answer_text: '<placeholder text>', question_id: '64', is_correct: false},
  {answer_id: '321', answer_text: '<placeholder text>', question_id: '65', is_correct: true},
  {answer_id: '322', answer_text: '<placeholder text>', question_id: '65', is_correct: false},
  {answer_id: '323', answer_text: '<placeholder text>', question_id: '65', is_correct: false},
  {answer_id: '324', answer_text: '<placeholder text>', question_id: '65', is_correct: false},
  {answer_id: '325', answer_text: '<placeholder text>', question_id: '65', is_correct: false},
  {answer_id: '326', answer_text: '<placeholder text>', question_id: '66', is_correct: true},
  {answer_id: '327', answer_text: '<placeholder text>', question_id: '66', is_correct: false},
  {answer_id: '328', answer_text: '<placeholder text>', question_id: '66', is_correct: false},
  {answer_id: '329', answer_text: '<placeholder text>', question_id: '66', is_correct: false},
  {answer_id: '330', answer_text: '<placeholder text>', question_id: '66', is_correct: false},
  {answer_id: '331', answer_text: '<placeholder text>', question_id: '67', is_correct: true},
  {answer_id: '332', answer_text: '<placeholder text>', question_id: '67', is_correct: false},
  {answer_id: '333', answer_text: '<placeholder text>', question_id: '67', is_correct: false},
  {answer_id: '334', answer_text: '<placeholder text>', question_id: '67', is_correct: false},
  {answer_id: '335', answer_text: '<placeholder text>', question_id: '67', is_correct: false},
  {answer_id: '336', answer_text: '<placeholder text>', question_id: '68', is_correct: true},
  {answer_id: '337', answer_text: '<placeholder text>', question_id: '68', is_correct: false},
  {answer_id: '338', answer_text: '<placeholder text>', question_id: '68', is_correct: false},
  {answer_id: '339', answer_text: '<placeholder text>', question_id: '68', is_correct: false},
  {answer_id: '340', answer_text: '<placeholder text>', question_id: '68', is_correct: false},
  {answer_id: '341', answer_text: '<placeholder text>', question_id: '69', is_correct: true},
  {answer_id: '342', answer_text: '<placeholder text>', question_id: '69', is_correct: false},
  {answer_id: '343', answer_text: '<placeholder text>', question_id: '69', is_correct: false},
  {answer_id: '344', answer_text: '<placeholder text>', question_id: '69', is_correct: false},
  {answer_id: '345', answer_text: '<placeholder text>', question_id: '69', is_correct: false},
  {answer_id: '346', answer_text: '<placeholder text>', question_id: '70', is_correct: true},
  {answer_id: '347', answer_text: '<placeholder text>', question_id: '70', is_correct: false},
  {answer_id: '348', answer_text: '<placeholder text>', question_id: '70', is_correct: false},
  {answer_id: '349', answer_text: '<placeholder text>', question_id: '70', is_correct: false},
  {answer_id: '350', answer_text: '<placeholder text>', question_id: '70', is_correct: false},
  {answer_id: '351', answer_text: '<placeholder text>', question_id: '71', is_correct: true},
  {answer_id: '352', answer_text: '<placeholder text>', question_id: '71', is_correct: false},
  {answer_id: '353', answer_text: '<placeholder text>', question_id: '71', is_correct: false},
  {answer_id: '354', answer_text: '<placeholder text>', question_id: '71', is_correct: false},
  {answer_id: '355', answer_text: '<placeholder text>', question_id: '71', is_correct: false},
  {answer_id: '356', answer_text: '<placeholder text>', question_id: '72', is_correct: true},
  {answer_id: '357', answer_text: '<placeholder text>', question_id: '72', is_correct: false},
  {answer_id: '358', answer_text: '<placeholder text>', question_id: '72', is_correct: false},
  {answer_id: '359', answer_text: '<placeholder text>', question_id: '72', is_correct: false},
  {answer_id: '360', answer_text: '<placeholder text>', question_id: '72', is_correct: false},
  {answer_id: '361', answer_text: '<placeholder text>', question_id: '73', is_correct: true},
  {answer_id: '362', answer_text: '<placeholder text>', question_id: '73', is_correct: false},
  {answer_id: '363', answer_text: '<placeholder text>', question_id: '73', is_correct: false},
  {answer_id: '364', answer_text: '<placeholder text>', question_id: '73', is_correct: false},
  {answer_id: '365', answer_text: '<placeholder text>', question_id: '73', is_correct: false},
  {answer_id: '366', answer_text: '<placeholder text>', question_id: '74', is_correct: true},
  {answer_id: '367', answer_text: '<placeholder text>', question_id: '74', is_correct: false},
  {answer_id: '368', answer_text: '<placeholder text>', question_id: '74', is_correct: false},
  {answer_id: '369', answer_text: '<placeholder text>', question_id: '74', is_correct: false},
  {answer_id: '370', answer_text: '<placeholder text>', question_id: '74', is_correct: false},
  {answer_id: '371', answer_text: '<placeholder text>', question_id: '75', is_correct: true},
  {answer_id: '372', answer_text: '<placeholder text>', question_id: '75', is_correct: false},
  {answer_id: '373', answer_text: '<placeholder text>', question_id: '75', is_correct: false},
  {answer_id: '374', answer_text: '<placeholder text>', question_id: '75', is_correct: false},
  {answer_id: '375', answer_text: '<placeholder text>', question_id: '75', is_correct: false},
  {answer_id: '376', answer_text: '<placeholder text>', question_id: '76', is_correct: true},
  {answer_id: '377', answer_text: '<placeholder text>', question_id: '76', is_correct: false},
  {answer_id: '378', answer_text: '<placeholder text>', question_id: '76', is_correct: false},
  {answer_id: '379', answer_text: '<placeholder text>', question_id: '76', is_correct: false},
  {answer_id: '380', answer_text: '<placeholder text>', question_id: '76', is_correct: false},
  {answer_id: '381', answer_text: '<placeholder text>', question_id: '77', is_correct: true},
  {answer_id: '382', answer_text: '<placeholder text>', question_id: '77', is_correct: false},
  {answer_id: '383', answer_text: '<placeholder text>', question_id: '77', is_correct: false},
  {answer_id: '384', answer_text: '<placeholder text>', question_id: '77', is_correct: false},
  {answer_id: '385', answer_text: '<placeholder text>', question_id: '77', is_correct: false},
  {answer_id: '386', answer_text: '<placeholder text>', question_id: '78', is_correct: true},
  {answer_id: '387', answer_text: '<placeholder text>', question_id: '78', is_correct: false},
  {answer_id: '388', answer_text: '<placeholder text>', question_id: '78', is_correct: false},
  {answer_id: '389', answer_text: '<placeholder text>', question_id: '78', is_correct: false},
  {answer_id: '390', answer_text: '<placeholder text>', question_id: '78', is_correct: false},
  {answer_id: '391', answer_text: '<placeholder text>', question_id: '79', is_correct: true},
  {answer_id: '392', answer_text: '<placeholder text>', question_id: '79', is_correct: false},
  {answer_id: '393', answer_text: '<placeholder text>', question_id: '79', is_correct: false},
  {answer_id: '394', answer_text: '<placeholder text>', question_id: '79', is_correct: false},
  {answer_id: '395', answer_text: '<placeholder text>', question_id: '79', is_correct: false},
  {answer_id: '396', answer_text: '<placeholder text>', question_id: '80', is_correct: true},
  {answer_id: '397', answer_text: '<placeholder text>', question_id: '80', is_correct: false},
  {answer_id: '398', answer_text: '<placeholder text>', question_id: '80', is_correct: false},
  {answer_id: '399', answer_text: '<placeholder text>', question_id: '80', is_correct: false},
  {answer_id: '400', answer_text: '<placeholder text>', question_id: '80', is_correct: false},
  {answer_id: '401', answer_text: '<placeholder text>', question_id: '81', is_correct: true},
  {answer_id: '402', answer_text: '<placeholder text>', question_id: '81', is_correct: false},
  {answer_id: '403', answer_text: '<placeholder text>', question_id: '81', is_correct: false},
  {answer_id: '404', answer_text: '<placeholder text>', question_id: '81', is_correct: false},
  {answer_id: '405', answer_text: '<placeholder text>', question_id: '81', is_correct: false},
  {answer_id: '406', answer_text: '<placeholder text>', question_id: '82', is_correct: true},
  {answer_id: '407', answer_text: '<placeholder text>', question_id: '82', is_correct: false},
  {answer_id: '408', answer_text: '<placeholder text>', question_id: '82', is_correct: false},
  {answer_id: '409', answer_text: '<placeholder text>', question_id: '82', is_correct: false},
  {answer_id: '410', answer_text: '<placeholder text>', question_id: '82', is_correct: false},
  {answer_id: '411', answer_text: '<placeholder text>', question_id: '83', is_correct: true},
  {answer_id: '412', answer_text: '<placeholder text>', question_id: '83', is_correct: false},
  {answer_id: '413', answer_text: '<placeholder text>', question_id: '83', is_correct: false},
  {answer_id: '414', answer_text: '<placeholder text>', question_id: '83', is_correct: false},
  {answer_id: '415', answer_text: '<placeholder text>', question_id: '83', is_correct: false},
  {answer_id: '416', answer_text: '<placeholder text>', question_id: '84', is_correct: true},
  {answer_id: '417', answer_text: '<placeholder text>', question_id: '84', is_correct: false},
  {answer_id: '418', answer_text: '<placeholder text>', question_id: '84', is_correct: false},
  {answer_id: '419', answer_text: '<placeholder text>', question_id: '84', is_correct: false},
  {answer_id: '420', answer_text: '<placeholder text>', question_id: '84', is_correct: false},
  {answer_id: '421', answer_text: '<placeholder text>', question_id: '85', is_correct: true},
  {answer_id: '422', answer_text: '<placeholder text>', question_id: '85', is_correct: false},
  {answer_id: '423', answer_text: '<placeholder text>', question_id: '85', is_correct: false},
  {answer_id: '424', answer_text: '<placeholder text>', question_id: '85', is_correct: false},
  {answer_id: '425', answer_text: '<placeholder text>', question_id: '85', is_correct: false},
  {answer_id: '426', answer_text: '<placeholder text>', question_id: '86', is_correct: true},
  {answer_id: '427', answer_text: '<placeholder text>', question_id: '86', is_correct: false},
  {answer_id: '428', answer_text: '<placeholder text>', question_id: '86', is_correct: false},
  {answer_id: '429', answer_text: '<placeholder text>', question_id: '86', is_correct: false},
  {answer_id: '430', answer_text: '<placeholder text>', question_id: '86', is_correct: false},
  {answer_id: '431', answer_text: '<placeholder text>', question_id: '87', is_correct: true},
  {answer_id: '432', answer_text: '<placeholder text>', question_id: '87', is_correct: false},
  {answer_id: '433', answer_text: '<placeholder text>', question_id: '87', is_correct: false},
  {answer_id: '434', answer_text: '<placeholder text>', question_id: '87', is_correct: false},
  {answer_id: '435', answer_text: '<placeholder text>', question_id: '87', is_correct: false},
  {answer_id: '436', answer_text: '<placeholder text>', question_id: '88', is_correct: true},
  {answer_id: '437', answer_text: '<placeholder text>', question_id: '88', is_correct: false},
  {answer_id: '438', answer_text: '<placeholder text>', question_id: '88', is_correct: false},
  {answer_id: '439', answer_text: '<placeholder text>', question_id: '88', is_correct: false},
  {answer_id: '440', answer_text: '<placeholder text>', question_id: '88', is_correct: false},
  {answer_id: '441', answer_text: '<placeholder text>', question_id: '89', is_correct: true},
  {answer_id: '442', answer_text: '<placeholder text>', question_id: '89', is_correct: false},
  {answer_id: '443', answer_text: '<placeholder text>', question_id: '89', is_correct: false},
  {answer_id: '444', answer_text: '<placeholder text>', question_id: '89', is_correct: false},
  {answer_id: '445', answer_text: '<placeholder text>', question_id: '89', is_correct: false},
  {answer_id: '446', answer_text: '<placeholder text>', question_id: '90', is_correct: true},
  {answer_id: '447', answer_text: '<placeholder text>', question_id: '90', is_correct: false},
  {answer_id: '448', answer_text: '<placeholder text>', question_id: '90', is_correct: false},
  {answer_id: '449', answer_text: '<placeholder text>', question_id: '90', is_correct: false},
  {answer_id: '450', answer_text: '<placeholder text>', question_id: '90', is_correct: false},
  {answer_id: '451', answer_text: '<placeholder text>', question_id: '91', is_correct: true},
  {answer_id: '452', answer_text: '<placeholder text>', question_id: '91', is_correct: false},
  {answer_id: '453', answer_text: '<placeholder text>', question_id: '91', is_correct: false},
  {answer_id: '454', answer_text: '<placeholder text>', question_id: '91', is_correct: false},
  {answer_id: '455', answer_text: '<placeholder text>', question_id: '91', is_correct: false},
  {answer_id: '456', answer_text: '<placeholder text>', question_id: '92', is_correct: true},
  {answer_id: '457', answer_text: '<placeholder text>', question_id: '92', is_correct: false},
  {answer_id: '458', answer_text: '<placeholder text>', question_id: '92', is_correct: false},
  {answer_id: '459', answer_text: '<placeholder text>', question_id: '92', is_correct: false},
  {answer_id: '460', answer_text: '<placeholder text>', question_id: '92', is_correct: false},
  {answer_id: '461', answer_text: '<placeholder text>', question_id: '93', is_correct: true},
  {answer_id: '462', answer_text: '<placeholder text>', question_id: '93', is_correct: false},
  {answer_id: '463', answer_text: '<placeholder text>', question_id: '93', is_correct: false},
  {answer_id: '464', answer_text: '<placeholder text>', question_id: '93', is_correct: false},
  {answer_id: '465', answer_text: '<placeholder text>', question_id: '93', is_correct: false},
  {answer_id: '466', answer_text: '<placeholder text>', question_id: '94', is_correct: true},
  {answer_id: '467', answer_text: '<placeholder text>', question_id: '94', is_correct: false},
  {answer_id: '468', answer_text: '<placeholder text>', question_id: '94', is_correct: false},
  {answer_id: '469', answer_text: '<placeholder text>', question_id: '94', is_correct: false},
  {answer_id: '470', answer_text: '<placeholder text>', question_id: '94', is_correct: false},
  {answer_id: '471', answer_text: '<placeholder text>', question_id: '95', is_correct: true},
  {answer_id: '472', answer_text: '<placeholder text>', question_id: '95', is_correct: false},
  {answer_id: '473', answer_text: '<placeholder text>', question_id: '95', is_correct: false},
  {answer_id: '474', answer_text: '<placeholder text>', question_id: '95', is_correct: false},
  {answer_id: '475', answer_text: '<placeholder text>', question_id: '95', is_correct: false},
  {answer_id: '476', answer_text: '<placeholder text>', question_id: '96', is_correct: true},
  {answer_id: '477', answer_text: '<placeholder text>', question_id: '96', is_correct: false},
  {answer_id: '478', answer_text: '<placeholder text>', question_id: '96', is_correct: false},
  {answer_id: '479', answer_text: '<placeholder text>', question_id: '96', is_correct: false},
  {answer_id: '480', answer_text: '<placeholder text>', question_id: '96', is_correct: false},
  {answer_id: '481', answer_text: '<placeholder text>', question_id: '97', is_correct: true},
  {answer_id: '482', answer_text: '<placeholder text>', question_id: '97', is_correct: false},
  {answer_id: '483', answer_text: '<placeholder text>', question_id: '97', is_correct: false},
  {answer_id: '484', answer_text: '<placeholder text>', question_id: '97', is_correct: false},
  {answer_id: '485', answer_text: '<placeholder text>', question_id: '97', is_correct: false},
  {answer_id: '486', answer_text: '<placeholder text>', question_id: '98', is_correct: true},
  {answer_id: '487', answer_text: '<placeholder text>', question_id: '98', is_correct: false},
  {answer_id: '488', answer_text: '<placeholder text>', question_id: '98', is_correct: false},
  {answer_id: '489', answer_text: '<placeholder text>', question_id: '98', is_correct: false},
  {answer_id: '490', answer_text: '<placeholder text>', question_id: '98', is_correct: false},
  {answer_id: '491', answer_text: '<placeholder text>', question_id: '99', is_correct: true},
  {answer_id: '492', answer_text: '<placeholder text>', question_id: '99', is_correct: false},
  {answer_id: '493', answer_text: '<placeholder text>', question_id: '99', is_correct: false},
  {answer_id: '494', answer_text: '<placeholder text>', question_id: '99', is_correct: false},
  {answer_id: '495', answer_text: '<placeholder text>', question_id: '99', is_correct: false},
  {answer_id: '496', answer_text: '<placeholder text>', question_id: '100', is_correct: true},
  {answer_id: '497', answer_text: '<placeholder text>', question_id: '100', is_correct: false},
  {answer_id: '498', answer_text: '<placeholder text>', question_id: '100', is_correct: false},
  {answer_id: '499', answer_text: '<placeholder text>', question_id: '100', is_correct: false},
  {answer_id: '500', answer_text: '<placeholder text>', question_id: '100', is_correct: false},
  {answer_id: '501', answer_text: '<placeholder text>', question_id: '101', is_correct: true},
  {answer_id: '502', answer_text: '<placeholder text>', question_id: '101', is_correct: false},
  {answer_id: '503', answer_text: '<placeholder text>', question_id: '101', is_correct: false},
  {answer_id: '504', answer_text: '<placeholder text>', question_id: '101', is_correct: false},
  {answer_id: '505', answer_text: '<placeholder text>', question_id: '101', is_correct: false},
  {answer_id: '506', answer_text: '<placeholder text>', question_id: '102', is_correct: true},
  {answer_id: '507', answer_text: '<placeholder text>', question_id: '102', is_correct: false},
  {answer_id: '508', answer_text: '<placeholder text>', question_id: '102', is_correct: false},
  {answer_id: '509', answer_text: '<placeholder text>', question_id: '102', is_correct: false},
  {answer_id: '510', answer_text: '<placeholder text>', question_id: '102', is_correct: false},
  {answer_id: '511', answer_text: '<placeholder text>', question_id: '103', is_correct: true},
  {answer_id: '512', answer_text: '<placeholder text>', question_id: '103', is_correct: false},
  {answer_id: '513', answer_text: '<placeholder text>', question_id: '103', is_correct: false},
  {answer_id: '514', answer_text: '<placeholder text>', question_id: '103', is_correct: false},
  {answer_id: '515', answer_text: '<placeholder text>', question_id: '103', is_correct: false},
  {answer_id: '516', answer_text: '<placeholder text>', question_id: '104', is_correct: true},
  {answer_id: '517', answer_text: '<placeholder text>', question_id: '104', is_correct: false},
  {answer_id: '518', answer_text: '<placeholder text>', question_id: '104', is_correct: false},
  {answer_id: '519', answer_text: '<placeholder text>', question_id: '104', is_correct: false},
  {answer_id: '520', answer_text: '<placeholder text>', question_id: '104', is_correct: false},
  {answer_id: '521', answer_text: '<placeholder text>', question_id: '105', is_correct: true},
  {answer_id: '522', answer_text: '<placeholder text>', question_id: '105', is_correct: false},
  {answer_id: '523', answer_text: '<placeholder text>', question_id: '105', is_correct: false},
  {answer_id: '524', answer_text: '<placeholder text>', question_id: '105', is_correct: false},
  {answer_id: '525', answer_text: '<placeholder text>', question_id: '105', is_correct: false},
  {answer_id: '526', answer_text: '<placeholder text>', question_id: '106', is_correct: true},
  {answer_id: '527', answer_text: '<placeholder text>', question_id: '106', is_correct: false},
  {answer_id: '528', answer_text: '<placeholder text>', question_id: '106', is_correct: false},
  {answer_id: '529', answer_text: '<placeholder text>', question_id: '106', is_correct: false},
  {answer_id: '530', answer_text: '<placeholder text>', question_id: '106', is_correct: false},
  {answer_id: '531', answer_text: '<placeholder text>', question_id: '107', is_correct: true},
  {answer_id: '532', answer_text: '<placeholder text>', question_id: '107', is_correct: false},
  {answer_id: '533', answer_text: '<placeholder text>', question_id: '107', is_correct: false},
  {answer_id: '534', answer_text: '<placeholder text>', question_id: '107', is_correct: false},
  {answer_id: '535', answer_text: '<placeholder text>', question_id: '107', is_correct: false},
  {answer_id: '536', answer_text: '<placeholder text>', question_id: '108', is_correct: true},
  {answer_id: '537', answer_text: '<placeholder text>', question_id: '108', is_correct: false},
  {answer_id: '538', answer_text: '<placeholder text>', question_id: '108', is_correct: false},
  {answer_id: '539', answer_text: '<placeholder text>', question_id: '108', is_correct: false},
  {answer_id: '540', answer_text: '<placeholder text>', question_id: '108', is_correct: false},
  {answer_id: '541', answer_text: '<placeholder text>', question_id: '109', is_correct: true},
  {answer_id: '542', answer_text: '<placeholder text>', question_id: '109', is_correct: false},
  {answer_id: '543', answer_text: '<placeholder text>', question_id: '109', is_correct: false},
  {answer_id: '544', answer_text: '<placeholder text>', question_id: '109', is_correct: false},
  {answer_id: '545', answer_text: '<placeholder text>', question_id: '109', is_correct: false},
  {answer_id: '546', answer_text: '<placeholder text>', question_id: '110', is_correct: true},
  {answer_id: '547', answer_text: '<placeholder text>', question_id: '110', is_correct: false},
  {answer_id: '548', answer_text: '<placeholder text>', question_id: '110', is_correct: false},
  {answer_id: '549', answer_text: '<placeholder text>', question_id: '110', is_correct: false},
  {answer_id: '550', answer_text: '<placeholder text>', question_id: '110', is_correct: false},
  {answer_id: '551', answer_text: '<placeholder text>', question_id: '111', is_correct: true},
  {answer_id: '552', answer_text: '<placeholder text>', question_id: '111', is_correct: false},
  {answer_id: '553', answer_text: '<placeholder text>', question_id: '111', is_correct: false},
  {answer_id: '554', answer_text: '<placeholder text>', question_id: '111', is_correct: false},
  {answer_id: '555', answer_text: '<placeholder text>', question_id: '111', is_correct: false},
  {answer_id: '556', answer_text: '<placeholder text>', question_id: '112', is_correct: true},
  {answer_id: '557', answer_text: '<placeholder text>', question_id: '112', is_correct: false},
  {answer_id: '558', answer_text: '<placeholder text>', question_id: '112', is_correct: false},
  {answer_id: '559', answer_text: '<placeholder text>', question_id: '112', is_correct: false},
  {answer_id: '560', answer_text: '<placeholder text>', question_id: '112', is_correct: false},
  {answer_id: '561', answer_text: '<placeholder text>', question_id: '113', is_correct: true},
  {answer_id: '562', answer_text: '<placeholder text>', question_id: '113', is_correct: false},
  {answer_id: '563', answer_text: '<placeholder text>', question_id: '113', is_correct: false},
  {answer_id: '564', answer_text: '<placeholder text>', question_id: '113', is_correct: false},
  {answer_id: '565', answer_text: '<placeholder text>', question_id: '113', is_correct: false},
  {answer_id: '566', answer_text: '<placeholder text>', question_id: '114', is_correct: true},
  {answer_id: '567', answer_text: '<placeholder text>', question_id: '114', is_correct: false},
  {answer_id: '568', answer_text: '<placeholder text>', question_id: '114', is_correct: false},
  {answer_id: '569', answer_text: '<placeholder text>', question_id: '114', is_correct: false},
  {answer_id: '570', answer_text: '<placeholder text>', question_id: '114', is_correct: false},
  {answer_id: '571', answer_text: '<placeholder text>', question_id: '115', is_correct: true},
  {answer_id: '572', answer_text: '<placeholder text>', question_id: '115', is_correct: false},
  {answer_id: '573', answer_text: '<placeholder text>', question_id: '115', is_correct: false},
  {answer_id: '574', answer_text: '<placeholder text>', question_id: '115', is_correct: false},
  {answer_id: '575', answer_text: '<placeholder text>', question_id: '115', is_correct: false},
  {answer_id: '576', answer_text: '<placeholder text>', question_id: '116', is_correct: true},
  {answer_id: '577', answer_text: '<placeholder text>', question_id: '116', is_correct: false},
  {answer_id: '578', answer_text: '<placeholder text>', question_id: '116', is_correct: false},
  {answer_id: '579', answer_text: '<placeholder text>', question_id: '116', is_correct: false},
  {answer_id: '580', answer_text: '<placeholder text>', question_id: '116', is_correct: false},
  {answer_id: '581', answer_text: '<placeholder text>', question_id: '117', is_correct: true},
  {answer_id: '582', answer_text: '<placeholder text>', question_id: '117', is_correct: false},
  {answer_id: '583', answer_text: '<placeholder text>', question_id: '117', is_correct: false},
  {answer_id: '584', answer_text: '<placeholder text>', question_id: '117', is_correct: false},
  {answer_id: '585', answer_text: '<placeholder text>', question_id: '117', is_correct: false},
  {answer_id: '586', answer_text: '<placeholder text>', question_id: '118', is_correct: true},
  {answer_id: '587', answer_text: '<placeholder text>', question_id: '118', is_correct: false},
  {answer_id: '588', answer_text: '<placeholder text>', question_id: '118', is_correct: false},
  {answer_id: '589', answer_text: '<placeholder text>', question_id: '118', is_correct: false},
  {answer_id: '590', answer_text: '<placeholder text>', question_id: '118', is_correct: false},
  {answer_id: '591', answer_text: '<placeholder text>', question_id: '119', is_correct: true},
  {answer_id: '592', answer_text: '<placeholder text>', question_id: '119', is_correct: false},
  {answer_id: '593', answer_text: '<placeholder text>', question_id: '119', is_correct: false},
  {answer_id: '594', answer_text: '<placeholder text>', question_id: '119', is_correct: false},
  {answer_id: '595', answer_text: '<placeholder text>', question_id: '119', is_correct: false},
  {answer_id: '596', answer_text: '<placeholder text>', question_id: '120', is_correct: true},
  {answer_id: '597', answer_text: '<placeholder text>', question_id: '120', is_correct: false},
  {answer_id: '598', answer_text: '<placeholder text>', question_id: '120', is_correct: false},
  {answer_id: '599', answer_text: '<placeholder text>', question_id: '120', is_correct: false},
  {answer_id: '600', answer_text: '<placeholder text>', question_id: '120', is_correct: false},
  {answer_id: '601', answer_text: '<placeholder text>', question_id: '121', is_correct: true},
  {answer_id: '602', answer_text: '<placeholder text>', question_id: '121', is_correct: false},
  {answer_id: '603', answer_text: '<placeholder text>', question_id: '121', is_correct: false},
  {answer_id: '604', answer_text: '<placeholder text>', question_id: '121', is_correct: false},
  {answer_id: '605', answer_text: '<placeholder text>', question_id: '121', is_correct: false},
  {answer_id: '606', answer_text: '<placeholder text>', question_id: '122', is_correct: true},
  {answer_id: '607', answer_text: '<placeholder text>', question_id: '122', is_correct: false},
  {answer_id: '608', answer_text: '<placeholder text>', question_id: '122', is_correct: false},
  {answer_id: '609', answer_text: '<placeholder text>', question_id: '122', is_correct: false},
  {answer_id: '610', answer_text: '<placeholder text>', question_id: '122', is_correct: false},
  {answer_id: '611', answer_text: '<placeholder text>', question_id: '123', is_correct: true},
  {answer_id: '612', answer_text: '<placeholder text>', question_id: '123', is_correct: false},
  {answer_id: '613', answer_text: '<placeholder text>', question_id: '123', is_correct: false},
  {answer_id: '614', answer_text: '<placeholder text>', question_id: '123', is_correct: false},
  {answer_id: '615', answer_text: '<placeholder text>', question_id: '123', is_correct: false},
  {answer_id: '616', answer_text: '<placeholder text>', question_id: '124', is_correct: true},
  {answer_id: '617', answer_text: '<placeholder text>', question_id: '124', is_correct: false},
  {answer_id: '618', answer_text: '<placeholder text>', question_id: '124', is_correct: false},
  {answer_id: '619', answer_text: '<placeholder text>', question_id: '124', is_correct: false},
  {answer_id: '620', answer_text: '<placeholder text>', question_id: '124', is_correct: false},
  {answer_id: '621', answer_text: '<placeholder text>', question_id: '125', is_correct: true},
  {answer_id: '622', answer_text: '<placeholder text>', question_id: '125', is_correct: false},
  {answer_id: '623', answer_text: '<placeholder text>', question_id: '125', is_correct: false},
  {answer_id: '624', answer_text: '<placeholder text>', question_id: '125', is_correct: false},
  {answer_id: '625', answer_text: '<placeholder text>', question_id: '125', is_correct: false},
  {answer_id: '626', answer_text: '<placeholder text>', question_id: '126', is_correct: true},
  {answer_id: '627', answer_text: '<placeholder text>', question_id: '126', is_correct: false},
  {answer_id: '628', answer_text: '<placeholder text>', question_id: '126', is_correct: false},
  {answer_id: '629', answer_text: '<placeholder text>', question_id: '126', is_correct: false},
  {answer_id: '630', answer_text: '<placeholder text>', question_id: '126', is_correct: false},
  {answer_id: '631', answer_text: '<placeholder text>', question_id: '127', is_correct: true},
  {answer_id: '632', answer_text: '<placeholder text>', question_id: '127', is_correct: false},
  {answer_id: '633', answer_text: '<placeholder text>', question_id: '127', is_correct: false},
  {answer_id: '634', answer_text: '<placeholder text>', question_id: '127', is_correct: false},
  {answer_id: '635', answer_text: '<placeholder text>', question_id: '127', is_correct: false},
  {answer_id: '636', answer_text: '<placeholder text>', question_id: '128', is_correct: true},
  {answer_id: '637', answer_text: '<placeholder text>', question_id: '128', is_correct: false},
  {answer_id: '638', answer_text: '<placeholder text>', question_id: '128', is_correct: false},
  {answer_id: '639', answer_text: '<placeholder text>', question_id: '128', is_correct: false},
  {answer_id: '640', answer_text: '<placeholder text>', question_id: '128', is_correct: false},
  {answer_id: '641', answer_text: '<placeholder text>', question_id: '129', is_correct: true},
  {answer_id: '642', answer_text: '<placeholder text>', question_id: '129', is_correct: false},
  {answer_id: '643', answer_text: '<placeholder text>', question_id: '129', is_correct: false},
  {answer_id: '644', answer_text: '<placeholder text>', question_id: '129', is_correct: false},
  {answer_id: '645', answer_text: '<placeholder text>', question_id: '129', is_correct: false},
  {answer_id: '646', answer_text: '<placeholder text>', question_id: '130', is_correct: true},
  {answer_id: '647', answer_text: '<placeholder text>', question_id: '130', is_correct: false},
  {answer_id: '648', answer_text: '<placeholder text>', question_id: '130', is_correct: false},
  {answer_id: '649', answer_text: '<placeholder text>', question_id: '130', is_correct: false},
  {answer_id: '650', answer_text: '<placeholder text>', question_id: '130', is_correct: false},
  {answer_id: '651', answer_text: '<placeholder text>', question_id: '131', is_correct: true},
  {answer_id: '652', answer_text: '<placeholder text>', question_id: '131', is_correct: false},
  {answer_id: '653', answer_text: '<placeholder text>', question_id: '131', is_correct: false},
  {answer_id: '654', answer_text: '<placeholder text>', question_id: '131', is_correct: false},
  {answer_id: '655', answer_text: '<placeholder text>', question_id: '131', is_correct: false},
  {answer_id: '656', answer_text: '<placeholder text>', question_id: '132', is_correct: true},
  {answer_id: '657', answer_text: '<placeholder text>', question_id: '132', is_correct: false},
  {answer_id: '658', answer_text: '<placeholder text>', question_id: '132', is_correct: false},
  {answer_id: '659', answer_text: '<placeholder text>', question_id: '132', is_correct: false},
  {answer_id: '660', answer_text: '<placeholder text>', question_id: '132', is_correct: false},
  {answer_id: '661', answer_text: '<placeholder text>', question_id: '133', is_correct: true},
  {answer_id: '662', answer_text: '<placeholder text>', question_id: '133', is_correct: false},
  {answer_id: '663', answer_text: '<placeholder text>', question_id: '133', is_correct: false},
  {answer_id: '664', answer_text: '<placeholder text>', question_id: '133', is_correct: false},
  {answer_id: '665', answer_text: '<placeholder text>', question_id: '133', is_correct: false},
  {answer_id: '666', answer_text: '<placeholder text>', question_id: '134', is_correct: true},
  {answer_id: '667', answer_text: '<placeholder text>', question_id: '134', is_correct: false},
  {answer_id: '668', answer_text: '<placeholder text>', question_id: '134', is_correct: false},
  {answer_id: '669', answer_text: '<placeholder text>', question_id: '134', is_correct: false},
  {answer_id: '670', answer_text: '<placeholder text>', question_id: '134', is_correct: false},
  {answer_id: '671', answer_text: '<placeholder text>', question_id: '135', is_correct: true},
  {answer_id: '672', answer_text: '<placeholder text>', question_id: '135', is_correct: false},
  {answer_id: '673', answer_text: '<placeholder text>', question_id: '135', is_correct: false},
  {answer_id: '674', answer_text: '<placeholder text>', question_id: '135', is_correct: false},
  {answer_id: '675', answer_text: '<placeholder text>', question_id: '135', is_correct: false},
]

// Option to update database with new questions and answers (maybe do an insert or ignore equivalent)
// Create endpoint for initiating quizzes for a user (take the username as an input and loop through quizzes to initiate)
//    Call this endpoint when a new user is created
//    Endpoint should also be able to "insert or ignore", so that new questions and answers can be added (when questions or answers are updated, loop through every user and call this endpoint)
// Add some logging to indicate what was updated

router.post('/initiate_quizzes', (req, res) => {
  Questions.remove({}, function(err) {});
  for(let i = 0; i < questions.length; i++) {
    var newQuestion = new Questions({
      question_id: questions[i].question_id,
      question_text: questions[i].question_text,
    })
    newQuestion.save(function(err, data) {
      if (err) {
        // TODO - add proper error handling here
      }
    })
  };
  Answers.remove({}, function(err) {});
  for(let i = 0; i < answers.length; i++) {
    var newAnswer = new Answers({
      answer_id: answers[i].answer_id,
      answer_text: answers[i].answer_text,
      question_id: answers[i].question_id,
      is_correct: answers[i].is_correct,
    })
    newAnswer.save(function(err, data) {
      if (err) {
        // TODO - add proper error handling here
      }
    })
  };
  res.json({success: true});
});

module.exports = router;
